/* CLDR 48 windowsZones.xml; Unicode license: LICENSE.unicode. */
static const struct { const char *iana; const wchar_t *windows; } luna_windows_zones[] = {
{"Africa/Abidjan",L"Greenwich Standard Time"},
{"Africa/Accra",L"Greenwich Standard Time"},
{"Africa/Addis_Ababa",L"E. Africa Standard Time"},
{"Africa/Algiers",L"W. Central Africa Standard Time"},
{"Africa/Asmera",L"E. Africa Standard Time"},
{"Africa/Bamako",L"Greenwich Standard Time"},
{"Africa/Bangui",L"W. Central Africa Standard Time"},
{"Africa/Banjul",L"Greenwich Standard Time"},
{"Africa/Bissau",L"Greenwich Standard Time"},
{"Africa/Blantyre",L"South Africa Standard Time"},
{"Africa/Brazzaville",L"W. Central Africa Standard Time"},
{"Africa/Bujumbura",L"South Africa Standard Time"},
{"Africa/Cairo",L"Egypt Standard Time"},
{"Africa/Casablanca",L"Morocco Standard Time"},
{"Africa/Ceuta",L"Romance Standard Time"},
{"Africa/Conakry",L"Greenwich Standard Time"},
{"Africa/Dakar",L"Greenwich Standard Time"},
{"Africa/Dar_es_Salaam",L"E. Africa Standard Time"},
{"Africa/Djibouti",L"E. Africa Standard Time"},
{"Africa/Douala",L"W. Central Africa Standard Time"},
{"Africa/El_Aaiun",L"Morocco Standard Time"},
{"Africa/Freetown",L"Greenwich Standard Time"},
{"Africa/Gaborone",L"South Africa Standard Time"},
{"Africa/Harare",L"South Africa Standard Time"},
{"Africa/Johannesburg",L"South Africa Standard Time"},
{"Africa/Juba",L"South Sudan Standard Time"},
{"Africa/Kampala",L"E. Africa Standard Time"},
{"Africa/Khartoum",L"Sudan Standard Time"},
{"Africa/Kigali",L"South Africa Standard Time"},
{"Africa/Kinshasa",L"W. Central Africa Standard Time"},
{"Africa/Lagos",L"W. Central Africa Standard Time"},
{"Africa/Libreville",L"W. Central Africa Standard Time"},
{"Africa/Lome",L"Greenwich Standard Time"},
{"Africa/Luanda",L"W. Central Africa Standard Time"},
{"Africa/Lubumbashi",L"South Africa Standard Time"},
{"Africa/Lusaka",L"South Africa Standard Time"},
{"Africa/Malabo",L"W. Central Africa Standard Time"},
{"Africa/Maputo",L"South Africa Standard Time"},
{"Africa/Maseru",L"South Africa Standard Time"},
{"Africa/Mbabane",L"South Africa Standard Time"},
{"Africa/Mogadishu",L"E. Africa Standard Time"},
{"Africa/Monrovia",L"Greenwich Standard Time"},
{"Africa/Nairobi",L"E. Africa Standard Time"},
{"Africa/Ndjamena",L"W. Central Africa Standard Time"},
{"Africa/Niamey",L"W. Central Africa Standard Time"},
{"Africa/Nouakchott",L"Greenwich Standard Time"},
{"Africa/Ouagadougou",L"Greenwich Standard Time"},
{"Africa/Porto-Novo",L"W. Central Africa Standard Time"},
{"Africa/Sao_Tome",L"Sao Tome Standard Time"},
{"Africa/Tripoli",L"Libya Standard Time"},
{"Africa/Tunis",L"W. Central Africa Standard Time"},
{"Africa/Windhoek",L"Namibia Standard Time"},
{"America/Adak",L"Aleutian Standard Time"},
{"America/Anchorage",L"Alaskan Standard Time"},
{"America/Anguilla",L"SA Western Standard Time"},
{"America/Antigua",L"SA Western Standard Time"},
{"America/Araguaina",L"Tocantins Standard Time"},
{"America/Argentina/Buenos_Aires",L"Argentina Standard Time"},
{"America/Argentina/La_Rioja",L"Argentina Standard Time"},
{"America/Argentina/Rio_Gallegos",L"Argentina Standard Time"},
{"America/Argentina/Salta",L"Argentina Standard Time"},
{"America/Argentina/San_Juan",L"Argentina Standard Time"},
{"America/Argentina/San_Luis",L"Argentina Standard Time"},
{"America/Argentina/Tucuman",L"Argentina Standard Time"},
{"America/Argentina/Ushuaia",L"Argentina Standard Time"},
{"America/Aruba",L"SA Western Standard Time"},
{"America/Asuncion",L"Paraguay Standard Time"},
{"America/Bahia",L"Bahia Standard Time"},
{"America/Bahia_Banderas",L"Central Standard Time (Mexico)"},
{"America/Barbados",L"SA Western Standard Time"},
{"America/Belem",L"SA Eastern Standard Time"},
{"America/Belize",L"Central America Standard Time"},
{"America/Blanc-Sablon",L"SA Western Standard Time"},
{"America/Boa_Vista",L"SA Western Standard Time"},
{"America/Bogota",L"SA Pacific Standard Time"},
{"America/Boise",L"Mountain Standard Time"},
{"America/Buenos_Aires",L"Argentina Standard Time"},
{"America/Cambridge_Bay",L"Mountain Standard Time"},
{"America/Campo_Grande",L"Central Brazilian Standard Time"},
{"America/Cancun",L"Eastern Standard Time (Mexico)"},
{"America/Caracas",L"Venezuela Standard Time"},
{"America/Catamarca",L"Argentina Standard Time"},
{"America/Cayenne",L"SA Eastern Standard Time"},
{"America/Cayman",L"SA Pacific Standard Time"},
{"America/Chicago",L"Central Standard Time"},
{"America/Chihuahua",L"Central Standard Time (Mexico)"},
{"America/Ciudad_Juarez",L"Mountain Standard Time"},
{"America/Coral_Harbour",L"SA Pacific Standard Time"},
{"America/Cordoba",L"Argentina Standard Time"},
{"America/Costa_Rica",L"Central America Standard Time"},
{"America/Coyhaique",L"Magallanes Standard Time"},
{"America/Creston",L"US Mountain Standard Time"},
{"America/Cuiaba",L"Central Brazilian Standard Time"},
{"America/Curacao",L"SA Western Standard Time"},
{"America/Danmarkshavn",L"Greenwich Standard Time"},
{"America/Dawson",L"Yukon Standard Time"},
{"America/Dawson_Creek",L"US Mountain Standard Time"},
{"America/Denver",L"Mountain Standard Time"},
{"America/Detroit",L"Eastern Standard Time"},
{"America/Dominica",L"SA Western Standard Time"},
{"America/Edmonton",L"Mountain Standard Time"},
{"America/Eirunepe",L"SA Pacific Standard Time"},
{"America/El_Salvador",L"Central America Standard Time"},
{"America/Fort_Nelson",L"US Mountain Standard Time"},
{"America/Fortaleza",L"SA Eastern Standard Time"},
{"America/Glace_Bay",L"Atlantic Standard Time"},
{"America/Godthab",L"Greenland Standard Time"},
{"America/Goose_Bay",L"Atlantic Standard Time"},
{"America/Grand_Turk",L"Turks And Caicos Standard Time"},
{"America/Grenada",L"SA Western Standard Time"},
{"America/Guadeloupe",L"SA Western Standard Time"},
{"America/Guatemala",L"Central America Standard Time"},
{"America/Guayaquil",L"SA Pacific Standard Time"},
{"America/Guyana",L"SA Western Standard Time"},
{"America/Halifax",L"Atlantic Standard Time"},
{"America/Havana",L"Cuba Standard Time"},
{"America/Hermosillo",L"US Mountain Standard Time"},
{"America/Indiana/Knox",L"Central Standard Time"},
{"America/Indiana/Marengo",L"US Eastern Standard Time"},
{"America/Indiana/Petersburg",L"Eastern Standard Time"},
{"America/Indiana/Tell_City",L"Central Standard Time"},
{"America/Indiana/Vevay",L"US Eastern Standard Time"},
{"America/Indiana/Vincennes",L"Eastern Standard Time"},
{"America/Indiana/Winamac",L"Eastern Standard Time"},
{"America/Indianapolis",L"US Eastern Standard Time"},
{"America/Inuvik",L"Mountain Standard Time"},
{"America/Iqaluit",L"Eastern Standard Time"},
{"America/Jamaica",L"SA Pacific Standard Time"},
{"America/Jujuy",L"Argentina Standard Time"},
{"America/Juneau",L"Alaskan Standard Time"},
{"America/Kentucky/Monticello",L"Eastern Standard Time"},
{"America/Kralendijk",L"SA Western Standard Time"},
{"America/La_Paz",L"SA Western Standard Time"},
{"America/Lima",L"SA Pacific Standard Time"},
{"America/Los_Angeles",L"Pacific Standard Time"},
{"America/Louisville",L"Eastern Standard Time"},
{"America/Lower_Princes",L"SA Western Standard Time"},
{"America/Maceio",L"SA Eastern Standard Time"},
{"America/Managua",L"Central America Standard Time"},
{"America/Manaus",L"SA Western Standard Time"},
{"America/Marigot",L"SA Western Standard Time"},
{"America/Martinique",L"SA Western Standard Time"},
{"America/Matamoros",L"Central Standard Time"},
{"America/Mazatlan",L"Mountain Standard Time (Mexico)"},
{"America/Mendoza",L"Argentina Standard Time"},
{"America/Menominee",L"Central Standard Time"},
{"America/Merida",L"Central Standard Time (Mexico)"},
{"America/Metlakatla",L"Alaskan Standard Time"},
{"America/Mexico_City",L"Central Standard Time (Mexico)"},
{"America/Miquelon",L"Saint Pierre Standard Time"},
{"America/Moncton",L"Atlantic Standard Time"},
{"America/Monterrey",L"Central Standard Time (Mexico)"},
{"America/Montevideo",L"Montevideo Standard Time"},
{"America/Montserrat",L"SA Western Standard Time"},
{"America/Nassau",L"Eastern Standard Time"},
{"America/New_York",L"Eastern Standard Time"},
{"America/Nome",L"Alaskan Standard Time"},
{"America/Noronha",L"UTC-02"},
{"America/North_Dakota/Beulah",L"Central Standard Time"},
{"America/North_Dakota/Center",L"Central Standard Time"},
{"America/North_Dakota/New_Salem",L"Central Standard Time"},
{"America/Ojinaga",L"Central Standard Time"},
{"America/Panama",L"SA Pacific Standard Time"},
{"America/Paramaribo",L"SA Eastern Standard Time"},
{"America/Phoenix",L"US Mountain Standard Time"},
{"America/Port-au-Prince",L"Haiti Standard Time"},
{"America/Port_of_Spain",L"SA Western Standard Time"},
{"America/Porto_Velho",L"SA Western Standard Time"},
{"America/Puerto_Rico",L"SA Western Standard Time"},
{"America/Punta_Arenas",L"Magallanes Standard Time"},
{"America/Rankin_Inlet",L"Central Standard Time"},
{"America/Recife",L"SA Eastern Standard Time"},
{"America/Regina",L"Canada Central Standard Time"},
{"America/Resolute",L"Central Standard Time"},
{"America/Rio_Branco",L"SA Pacific Standard Time"},
{"America/Santarem",L"SA Eastern Standard Time"},
{"America/Santiago",L"Pacific SA Standard Time"},
{"America/Santo_Domingo",L"SA Western Standard Time"},
{"America/Sao_Paulo",L"E. South America Standard Time"},
{"America/Scoresbysund",L"Azores Standard Time"},
{"America/Sitka",L"Alaskan Standard Time"},
{"America/St_Barthelemy",L"SA Western Standard Time"},
{"America/St_Johns",L"Newfoundland Standard Time"},
{"America/St_Kitts",L"SA Western Standard Time"},
{"America/St_Lucia",L"SA Western Standard Time"},
{"America/St_Thomas",L"SA Western Standard Time"},
{"America/St_Vincent",L"SA Western Standard Time"},
{"America/Swift_Current",L"Canada Central Standard Time"},
{"America/Tegucigalpa",L"Central America Standard Time"},
{"America/Thule",L"Atlantic Standard Time"},
{"America/Tijuana",L"Pacific Standard Time (Mexico)"},
{"America/Toronto",L"Eastern Standard Time"},
{"America/Tortola",L"SA Western Standard Time"},
{"America/Vancouver",L"Pacific Standard Time"},
{"America/Whitehorse",L"Yukon Standard Time"},
{"America/Winnipeg",L"Central Standard Time"},
{"America/Yakutat",L"Alaskan Standard Time"},
{"Antarctica/Casey",L"Central Pacific Standard Time"},
{"Antarctica/Davis",L"SE Asia Standard Time"},
{"Antarctica/DumontDUrville",L"West Pacific Standard Time"},
{"Antarctica/Macquarie",L"Tasmania Standard Time"},
{"Antarctica/Mawson",L"West Asia Standard Time"},
{"Antarctica/McMurdo",L"New Zealand Standard Time"},
{"Antarctica/Palmer",L"SA Eastern Standard Time"},
{"Antarctica/Rothera",L"SA Eastern Standard Time"},
{"Antarctica/Syowa",L"E. Africa Standard Time"},
{"Antarctica/Vostok",L"Central Asia Standard Time"},
{"Arctic/Longyearbyen",L"W. Europe Standard Time"},
{"Asia/Aden",L"Arab Standard Time"},
{"Asia/Almaty",L"West Asia Standard Time"},
{"Asia/Amman",L"Jordan Standard Time"},
{"Asia/Anadyr",L"Russia Time Zone 11"},
{"Asia/Aqtau",L"West Asia Standard Time"},
{"Asia/Aqtobe",L"West Asia Standard Time"},
{"Asia/Ashgabat",L"West Asia Standard Time"},
{"Asia/Atyrau",L"West Asia Standard Time"},
{"Asia/Baghdad",L"Arabic Standard Time"},
{"Asia/Bahrain",L"Arab Standard Time"},
{"Asia/Baku",L"Azerbaijan Standard Time"},
{"Asia/Bangkok",L"SE Asia Standard Time"},
{"Asia/Barnaul",L"Altai Standard Time"},
{"Asia/Beirut",L"Middle East Standard Time"},
{"Asia/Bishkek",L"Central Asia Standard Time"},
{"Asia/Brunei",L"Singapore Standard Time"},
{"Asia/Calcutta",L"India Standard Time"},
{"Asia/Chita",L"Transbaikal Standard Time"},
{"Asia/Colombo",L"Sri Lanka Standard Time"},
{"Asia/Damascus",L"Syria Standard Time"},
{"Asia/Dhaka",L"Bangladesh Standard Time"},
{"Asia/Dili",L"Tokyo Standard Time"},
{"Asia/Dubai",L"Arabian Standard Time"},
{"Asia/Dushanbe",L"West Asia Standard Time"},
{"Asia/Famagusta",L"GTB Standard Time"},
{"Asia/Gaza",L"West Bank Standard Time"},
{"Asia/Hebron",L"West Bank Standard Time"},
{"Asia/Hong_Kong",L"China Standard Time"},
{"Asia/Hovd",L"W. Mongolia Standard Time"},
{"Asia/Irkutsk",L"North Asia East Standard Time"},
{"Asia/Jakarta",L"SE Asia Standard Time"},
{"Asia/Jayapura",L"Tokyo Standard Time"},
{"Asia/Jerusalem",L"Israel Standard Time"},
{"Asia/Kabul",L"Afghanistan Standard Time"},
{"Asia/Kamchatka",L"Russia Time Zone 11"},
{"Asia/Karachi",L"Pakistan Standard Time"},
{"Asia/Katmandu",L"Nepal Standard Time"},
{"Asia/Khandyga",L"Yakutsk Standard Time"},
{"Asia/Kolkata",L"India Standard Time"},
{"Asia/Krasnoyarsk",L"North Asia Standard Time"},
{"Asia/Kuala_Lumpur",L"Singapore Standard Time"},
{"Asia/Kuching",L"Singapore Standard Time"},
{"Asia/Kuwait",L"Arab Standard Time"},
{"Asia/Macau",L"China Standard Time"},
{"Asia/Magadan",L"Magadan Standard Time"},
{"Asia/Makassar",L"Singapore Standard Time"},
{"Asia/Manila",L"Singapore Standard Time"},
{"Asia/Muscat",L"Arabian Standard Time"},
{"Asia/Nicosia",L"GTB Standard Time"},
{"Asia/Novokuznetsk",L"North Asia Standard Time"},
{"Asia/Novosibirsk",L"N. Central Asia Standard Time"},
{"Asia/Omsk",L"Omsk Standard Time"},
{"Asia/Oral",L"West Asia Standard Time"},
{"Asia/Phnom_Penh",L"SE Asia Standard Time"},
{"Asia/Pontianak",L"SE Asia Standard Time"},
{"Asia/Pyongyang",L"North Korea Standard Time"},
{"Asia/Qatar",L"Arab Standard Time"},
{"Asia/Qostanay",L"West Asia Standard Time"},
{"Asia/Qyzylorda",L"Qyzylorda Standard Time"},
{"Asia/Rangoon",L"Myanmar Standard Time"},
{"Asia/Riyadh",L"Arab Standard Time"},
{"Asia/Saigon",L"SE Asia Standard Time"},
{"Asia/Sakhalin",L"Sakhalin Standard Time"},
{"Asia/Samarkand",L"West Asia Standard Time"},
{"Asia/Seoul",L"Korea Standard Time"},
{"Asia/Shanghai",L"China Standard Time"},
{"Asia/Singapore",L"Singapore Standard Time"},
{"Asia/Srednekolymsk",L"Russia Time Zone 10"},
{"Asia/Taipei",L"Taipei Standard Time"},
{"Asia/Tashkent",L"West Asia Standard Time"},
{"Asia/Tbilisi",L"Georgian Standard Time"},
{"Asia/Tehran",L"Iran Standard Time"},
{"Asia/Thimphu",L"Bangladesh Standard Time"},
{"Asia/Tokyo",L"Tokyo Standard Time"},
{"Asia/Tomsk",L"Tomsk Standard Time"},
{"Asia/Ulaanbaatar",L"Ulaanbaatar Standard Time"},
{"Asia/Urumqi",L"Central Asia Standard Time"},
{"Asia/Ust-Nera",L"Vladivostok Standard Time"},
{"Asia/Vientiane",L"SE Asia Standard Time"},
{"Asia/Vladivostok",L"Vladivostok Standard Time"},
{"Asia/Yakutsk",L"Yakutsk Standard Time"},
{"Asia/Yekaterinburg",L"Ekaterinburg Standard Time"},
{"Asia/Yerevan",L"Caucasus Standard Time"},
{"Atlantic/Azores",L"Azores Standard Time"},
{"Atlantic/Bermuda",L"Atlantic Standard Time"},
{"Atlantic/Canary",L"GMT Standard Time"},
{"Atlantic/Cape_Verde",L"Cape Verde Standard Time"},
{"Atlantic/Faeroe",L"GMT Standard Time"},
{"Atlantic/Madeira",L"GMT Standard Time"},
{"Atlantic/Reykjavik",L"Greenwich Standard Time"},
{"Atlantic/South_Georgia",L"UTC-02"},
{"Atlantic/St_Helena",L"Greenwich Standard Time"},
{"Atlantic/Stanley",L"SA Eastern Standard Time"},
{"Australia/Adelaide",L"Cen. Australia Standard Time"},
{"Australia/Brisbane",L"E. Australia Standard Time"},
{"Australia/Broken_Hill",L"Cen. Australia Standard Time"},
{"Australia/Darwin",L"AUS Central Standard Time"},
{"Australia/Eucla",L"Aus Central W. Standard Time"},
{"Australia/Hobart",L"Tasmania Standard Time"},
{"Australia/Lindeman",L"E. Australia Standard Time"},
{"Australia/Lord_Howe",L"Lord Howe Standard Time"},
{"Australia/Melbourne",L"AUS Eastern Standard Time"},
{"Australia/Perth",L"W. Australia Standard Time"},
{"Australia/Sydney",L"AUS Eastern Standard Time"},
{"Etc/GMT",L"UTC"},
{"Etc/GMT+1",L"Cape Verde Standard Time"},
{"Etc/GMT+10",L"Hawaiian Standard Time"},
{"Etc/GMT+11",L"UTC-11"},
{"Etc/GMT+12",L"Dateline Standard Time"},
{"Etc/GMT+2",L"UTC-02"},
{"Etc/GMT+3",L"SA Eastern Standard Time"},
{"Etc/GMT+4",L"SA Western Standard Time"},
{"Etc/GMT+5",L"SA Pacific Standard Time"},
{"Etc/GMT+6",L"Central America Standard Time"},
{"Etc/GMT+7",L"US Mountain Standard Time"},
{"Etc/GMT+8",L"UTC-08"},
{"Etc/GMT+9",L"UTC-09"},
{"Etc/GMT-1",L"W. Central Africa Standard Time"},
{"Etc/GMT-10",L"West Pacific Standard Time"},
{"Etc/GMT-11",L"Central Pacific Standard Time"},
{"Etc/GMT-12",L"UTC+12"},
{"Etc/GMT-13",L"UTC+13"},
{"Etc/GMT-14",L"Line Islands Standard Time"},
{"Etc/GMT-2",L"South Africa Standard Time"},
{"Etc/GMT-3",L"E. Africa Standard Time"},
{"Etc/GMT-4",L"Arabian Standard Time"},
{"Etc/GMT-5",L"West Asia Standard Time"},
{"Etc/GMT-6",L"Central Asia Standard Time"},
{"Etc/GMT-7",L"SE Asia Standard Time"},
{"Etc/GMT-8",L"Singapore Standard Time"},
{"Etc/GMT-9",L"Tokyo Standard Time"},
{"Etc/UTC",L"UTC"},
{"Europe/Amsterdam",L"W. Europe Standard Time"},
{"Europe/Andorra",L"W. Europe Standard Time"},
{"Europe/Astrakhan",L"Astrakhan Standard Time"},
{"Europe/Athens",L"GTB Standard Time"},
{"Europe/Belgrade",L"Central Europe Standard Time"},
{"Europe/Berlin",L"W. Europe Standard Time"},
{"Europe/Bratislava",L"Central Europe Standard Time"},
{"Europe/Brussels",L"Romance Standard Time"},
{"Europe/Bucharest",L"GTB Standard Time"},
{"Europe/Budapest",L"Central Europe Standard Time"},
{"Europe/Busingen",L"W. Europe Standard Time"},
{"Europe/Chisinau",L"E. Europe Standard Time"},
{"Europe/Copenhagen",L"Romance Standard Time"},
{"Europe/Dublin",L"GMT Standard Time"},
{"Europe/Gibraltar",L"W. Europe Standard Time"},
{"Europe/Guernsey",L"GMT Standard Time"},
{"Europe/Helsinki",L"FLE Standard Time"},
{"Europe/Isle_of_Man",L"GMT Standard Time"},
{"Europe/Istanbul",L"Turkey Standard Time"},
{"Europe/Jersey",L"GMT Standard Time"},
{"Europe/Kaliningrad",L"Kaliningrad Standard Time"},
{"Europe/Kiev",L"FLE Standard Time"},
{"Europe/Kirov",L"Russian Standard Time"},
{"Europe/Kyiv",L"FLE Standard Time"},
{"Europe/Lisbon",L"GMT Standard Time"},
{"Europe/Ljubljana",L"Central Europe Standard Time"},
{"Europe/London",L"GMT Standard Time"},
{"Europe/Luxembourg",L"W. Europe Standard Time"},
{"Europe/Madrid",L"Romance Standard Time"},
{"Europe/Malta",L"W. Europe Standard Time"},
{"Europe/Mariehamn",L"FLE Standard Time"},
{"Europe/Minsk",L"Belarus Standard Time"},
{"Europe/Monaco",L"W. Europe Standard Time"},
{"Europe/Moscow",L"Russian Standard Time"},
{"Europe/Oslo",L"W. Europe Standard Time"},
{"Europe/Paris",L"Romance Standard Time"},
{"Europe/Podgorica",L"Central Europe Standard Time"},
{"Europe/Prague",L"Central Europe Standard Time"},
{"Europe/Riga",L"FLE Standard Time"},
{"Europe/Rome",L"W. Europe Standard Time"},
{"Europe/Samara",L"Russia Time Zone 3"},
{"Europe/San_Marino",L"W. Europe Standard Time"},
{"Europe/Sarajevo",L"Central European Standard Time"},
{"Europe/Saratov",L"Saratov Standard Time"},
{"Europe/Simferopol",L"Russian Standard Time"},
{"Europe/Skopje",L"Central European Standard Time"},
{"Europe/Sofia",L"FLE Standard Time"},
{"Europe/Stockholm",L"W. Europe Standard Time"},
{"Europe/Tallinn",L"FLE Standard Time"},
{"Europe/Tirane",L"Central Europe Standard Time"},
{"Europe/Ulyanovsk",L"Astrakhan Standard Time"},
{"Europe/Vaduz",L"W. Europe Standard Time"},
{"Europe/Vatican",L"W. Europe Standard Time"},
{"Europe/Vienna",L"W. Europe Standard Time"},
{"Europe/Vilnius",L"FLE Standard Time"},
{"Europe/Volgograd",L"Volgograd Standard Time"},
{"Europe/Warsaw",L"Central European Standard Time"},
{"Europe/Zagreb",L"Central European Standard Time"},
{"Europe/Zurich",L"W. Europe Standard Time"},
{"GMT",L"UTC"},
{"Indian/Antananarivo",L"E. Africa Standard Time"},
{"Indian/Chagos",L"Central Asia Standard Time"},
{"Indian/Christmas",L"SE Asia Standard Time"},
{"Indian/Cocos",L"Myanmar Standard Time"},
{"Indian/Comoro",L"E. Africa Standard Time"},
{"Indian/Kerguelen",L"West Asia Standard Time"},
{"Indian/Mahe",L"Mauritius Standard Time"},
{"Indian/Maldives",L"West Asia Standard Time"},
{"Indian/Mauritius",L"Mauritius Standard Time"},
{"Indian/Mayotte",L"E. Africa Standard Time"},
{"Indian/Reunion",L"Mauritius Standard Time"},
{"Japan",L"Tokyo Standard Time"},
{"Pacific/Apia",L"Samoa Standard Time"},
{"Pacific/Auckland",L"New Zealand Standard Time"},
{"Pacific/Bougainville",L"Bougainville Standard Time"},
{"Pacific/Chatham",L"Chatham Islands Standard Time"},
{"Pacific/Easter",L"Easter Island Standard Time"},
{"Pacific/Efate",L"Central Pacific Standard Time"},
{"Pacific/Enderbury",L"UTC+13"},
{"Pacific/Fakaofo",L"UTC+13"},
{"Pacific/Fiji",L"Fiji Standard Time"},
{"Pacific/Funafuti",L"UTC+12"},
{"Pacific/Galapagos",L"Central America Standard Time"},
{"Pacific/Gambier",L"UTC-09"},
{"Pacific/Guadalcanal",L"Central Pacific Standard Time"},
{"Pacific/Guam",L"West Pacific Standard Time"},
{"Pacific/Honolulu",L"Hawaiian Standard Time"},
{"Pacific/Kiritimati",L"Line Islands Standard Time"},
{"Pacific/Kosrae",L"Central Pacific Standard Time"},
{"Pacific/Kwajalein",L"UTC+12"},
{"Pacific/Majuro",L"UTC+12"},
{"Pacific/Marquesas",L"Marquesas Standard Time"},
{"Pacific/Midway",L"UTC-11"},
{"Pacific/Nauru",L"UTC+12"},
{"Pacific/Niue",L"UTC-11"},
{"Pacific/Norfolk",L"Norfolk Standard Time"},
{"Pacific/Noumea",L"Central Pacific Standard Time"},
{"Pacific/Pago_Pago",L"UTC-11"},
{"Pacific/Palau",L"Tokyo Standard Time"},
{"Pacific/Pitcairn",L"UTC-08"},
{"Pacific/Ponape",L"Central Pacific Standard Time"},
{"Pacific/Port_Moresby",L"West Pacific Standard Time"},
{"Pacific/Rarotonga",L"Hawaiian Standard Time"},
{"Pacific/Saipan",L"West Pacific Standard Time"},
{"Pacific/Tahiti",L"Hawaiian Standard Time"},
{"Pacific/Tarawa",L"UTC+12"},
{"Pacific/Tongatapu",L"Tonga Standard Time"},
{"Pacific/Truk",L"West Pacific Standard Time"},
{"Pacific/Wake",L"UTC+12"},
{"Pacific/Wallis",L"UTC+12"},
{"US/Eastern",L"Eastern Standard Time"},
{"US/Pacific",L"Pacific Standard Time"},
{"UTC",L"UTC"},
};
