#!/usr/bin/env python3
#
# Copyright © 2026 Yuichiro Nakada / Project Lunaria
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Generates src/luna_vulkan_cmds.h from the Vulkan registry (vk.xml): one row
# per Vulkan command, with what the guest-to-host call bridge needs to know
# about its arguments.  The output is checked in; rerun this when the headers
# the build uses are updated:
#
#     python3 scripts/gen_vk_commands.py /usr/share/vulkan/registry/vk.xml \
#         > src/luna_vulkan_cmds.h
#
# Per command:
#   - how many parameters it takes,
#   - which of them are `float` by value (AArch64 passes those in v0-v7 and
#     x86-64 in xmm0-7, apart from the integer ones),
#   - which one, if any, is `const VkAllocationCallbacks* pAllocator` (the
#     callbacks are guest code, which the host driver cannot call),
#   - the dispatch level from the first parameter's type,
#   - the return kind.
# A command that takes a struct by value, or more than 16 integer-class or 8
# float parameters, cannot go through the generic bridge; the generator stops
# rather than emit a row that would be called wrongly.

import sys
import xml.etree.ElementTree as ET

INSTANCE_HANDLES = {"VkInstance", "VkPhysicalDevice"}
DEVICE_HANDLES = {"VkDevice", "VkQueue", "VkCommandBuffer", "VkExternalComputeQueueNV"}


def text_of(elem):
    return "".join(elem.itertext())


def main():
    tree = ET.parse(sys.argv[1])
    root = tree.getroot()

    struct_types = set()
    for t in root.iter("type"):
        if t.get("category") in ("struct", "union"):
            name = t.get("name")
            if name:
                struct_types.add(name)

    commands = {}
    aliases = []
    for cmd in root.find("commands").findall("command"):
        api = cmd.get("api")
        if api and "vulkan" not in api.split(","):
            continue
        if cmd.get("alias"):
            aliases.append((cmd.get("name"), cmd.get("alias")))
            continue
        proto = cmd.find("proto")
        name = proto.find("name").text
        ret = proto.find("type").text
        params = []
        for p in cmd.findall("param"):
            papi = p.get("api")
            if papi and "vulkan" not in papi.split(","):
                continue
            ptype = p.find("type").text
            pname = p.find("name").text
            full = text_of(p)
            pointer = "*" in full or "[" in full
            params.append((ptype, pname, pointer))
        commands[name] = (ret, params)
    for name, target in aliases:
        if target in commands and name not in commands:
            commands[name] = commands[target]

    rows = []
    for name in sorted(commands):
        ret, params = commands[name]
        n = len(params)
        float_mask = 0
        n_int = n_float = 0
        alloc = -1
        for i, (ptype, pname, pointer) in enumerate(params):
            if not pointer and ptype in struct_types:
                sys.exit(f"{name}: parameter {pname} is a {ptype} by value")
            if not pointer and ptype in ("float", "double"):
                if ptype == "double":
                    sys.exit(f"{name}: double parameter {pname}")
                float_mask |= 1 << i
                n_float += 1
            else:
                n_int += 1
            if ptype == "VkAllocationCallbacks" and pointer:
                alloc = i
        if n_int > 16 or n_float > 8:
            sys.exit(f"{name}: {n_int} integer / {n_float} float parameters")
        first = params[0][0] if params else ""
        level = ("LVK_DEVICE" if first in DEVICE_HANDLES else
                 "LVK_INSTANCE" if first in INSTANCE_HANDLES else "LVK_GLOBAL")
        if ret == "void":
            rkind = "LVK_RET_VOID"
        elif ret == "VkResult":
            rkind = "LVK_RET_RESULT"
        elif ret.startswith("PFN_"):
            rkind = "LVK_RET_PFN"
        elif ret in ("float",):
            sys.exit(f"{name}: float return")
        else:
            rkind = "LVK_RET_INT"
        rows.append((name, n, float_mask, alloc, level, rkind))

    out = sys.stdout
    out.write("/* Generated by scripts/gen_vk_commands.py from vk.xml — do not edit.\n"
              " * See that script for what each column means. */\n")
    out.write("#ifndef LUNARIA_LUNA_VULKAN_CMDS_H\n#define LUNARIA_LUNA_VULKAN_CMDS_H\n\n")
    out.write("static const struct lvk_cmd lvk_cmds[] = {\n")
    for name, n, fmask, alloc, level, rkind in rows:
        out.write(f'   {{ "{name}", {n}, 0x{fmask:x}u, {alloc}, {level}, {rkind} }},\n')
    out.write("};\n\n#endif\n")
    sys.stderr.write(f"{len(rows)} commands\n")


if __name__ == "__main__":
    main()
