/* Generated by scripts/framework-strings.py from AOSP framework-res.
 * Copyright 2006 The Android Open Source Project
 * Licensed under the Apache License, Version 2.0.
 * https://www.apache.org/licenses/LICENSE-2.0
 * Default-locale public strings; package 0x01 belongs to Android.
 */
#ifndef LUNA_FRAMEWORK_STRINGS_H
#define LUNA_FRAMEWORK_STRINGS_H
#include <stdint.h>
#include <stddef.h>
#include <string.h>
static const struct { uint32_t id; const char *name, *value; } luna_framework_strings[] = {
    {0x01040000u, "cancel", "Cancel"},
    {0x01040001u, "copy", "Copy"},
    {0x01040002u, "copyUrl", "Copy URL"},
    {0x01040003u, "cut", "Cut"},
    {0x01040004u, "defaultVoiceMailAlphaTag", "Voicemail"},
    {0x01040005u, "defaultMsisdnAlphaTag", "MSISDN1"},
    {0x01040006u, "emptyPhoneNumber", "(No phone number)"},
    {0x01040007u, "httpErrorBadUrl", "Couldn't open the page because the URL is invalid."},
    {0x01040008u, "httpErrorUnsupportedScheme", "The protocol isn't supported."},
    {0x01040009u, "no", "Cancel"},
    {0x0104000au, "ok", "OK"},
    {0x0104000bu, "paste", "Paste"},
    {0x0104000cu, "search_go", "Search"},
    {0x0104000du, "selectAll", "Select all"},
    {0x0104000eu, "unknownName", "Unknown"},
    {0x0104000fu, "untitled", "<Untitled>"},
    {0x01040010u, "VideoView_error_button", "OK"},
    {0x01040011u, "VideoView_error_text_unknown", "Can't play this video."},
    {0x01040012u, "VideoView_error_title", "Video problem"},
    {0x01040013u, "yes", "OK"},
    {0x01040014u, "dialog_alert_title", "Attention"},
    {0x01040015u, "VideoView_error_text_invalid_progressive_playback", "This video isn't valid for streaming to this device."},
    {0x01040016u, "selectTextMode", "Select text"},
    {0x01040017u, "status_bar_notification_info_overflow", "999+"},
    {0x01040018u, "fingerprint_icon_content_description", "Fingerprint icon"},
    {0x01040019u, "paste_as_plain_text", "Paste as plain text"},
    {0x0104001au, "autofill", "Autofill"},
    {0x0104001bu, "config_helpPackageNameKey", ""},
    {0x0104001cu, "config_helpPackageNameValue", ""},
    {0x0104001du, "config_helpIntentExtraKey", ""},
    {0x0104001eu, "config_helpIntentNameKey", ""},
    {0x0104001fu, "config_feedbackIntentExtraKey", ""},
    {0x01040020u, "config_feedbackIntentNameKey", ""},
    {0x01040021u, "config_defaultAssistant", ""},
    {0x01040022u, "config_defaultBrowser", ""},
    {0x01040023u, "config_defaultDialer", "com.android.dialer"},
    {0x01040024u, "config_defaultSms", "com.android.messaging"},
    {0x01040025u, "config_defaultCallRedirection", ""},
    {0x01040026u, "config_defaultCallScreening", ""},
    {0x01040027u, "config_systemGallery", "com.android.gallery3d"},
    {0x01040028u, "config_systemAutomotiveCluster", ""},
    {0x01040029u, "config_systemAutomotiveProjection", ""},
    {0x0104002au, "config_systemShell", "com.android.shell"},
    {0x0104002bu, "config_systemContacts", "com.android.contacts"},
    {0x0104002cu, "config_customMediaKeyDispatcher", ""},
    {0x0104002du, "config_customMediaSessionPolicyProvider", ""},
    {0x0104002eu, "config_systemSpeechRecognizer", ""},
    {0x0104002fu, "config_systemWifiCoexManager", ""},
    {0x01040030u, "config_systemWellbeing", ""},
    {0x01040031u, "config_systemTelevisionNotificationHandler", ""},
    {0x01040032u, "config_systemUiIntelligence", ""},
    {0x01040033u, "config_systemAmbientAudioIntelligence", ""},
    {0x01040034u, "config_systemAudioIntelligence", ""},
    {0x01040035u, "config_systemNotificationIntelligence", ""},
    {0x01040036u, "config_systemTextIntelligence", ""},
    {0x01040037u, "config_systemVisualIntelligence", ""},
    {0x01040038u, "config_systemActivityRecognizer", ""},
    {0x01040039u, "config_systemCompanionDeviceProvider", ""},
    {0x0104003au, "config_systemUi", "com.android.systemui"},
    {0x0104003bu, "config_defaultRingtoneVibrationSound", ""},
};
static inline uint32_t luna_framework_string_id(const char *name)
{
    for (size_t i=0; i<sizeof luna_framework_strings/sizeof *luna_framework_strings; ++i)
        if (name && !strcmp(name,luna_framework_strings[i].name)) return luna_framework_strings[i].id;
    return 0;
}
static inline const char *luna_framework_string_value(uint32_t id)
{
    for (size_t i=0; i<sizeof luna_framework_strings/sizeof *luna_framework_strings; ++i)
        if (id==luna_framework_strings[i].id) return luna_framework_strings[i].value;
    return NULL;
}
#endif
